export const keyConstant = {
	login: 'login',
	register: 'register',
	get_me: 'get-me',
	logout: 'logout',
	get_users: 'get-all-users',
	get_user: 'get-user-by-id',
	create_user: 'create-user',
	edit_user: 'edit-user',
	delete_user: 'delete-user',
	toggle_user: 'toggle-user',
	get_user_for_select: 'get-user-for-select',
	get_roles: 'get-all-roles',
	get_role: 'get-role-by-id',
	create_role: 'create-role',
	edit_role: 'edit-role',
	delete_role: 'delete-role',
	toggle_role: 'toggle-role',
	get_role_for_select: 'get-role-for-select'
} as const
