name: deploying-to-production

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - '.env'
      - 'index.html'
      - 'postcss.config.js'
      - 'pnpm-lock.yaml'
      - 'tailwind.config.js'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'vite.config.ts'
      - '.github/workflows/deploying-to-production.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Find repository"
            cd /home/bloomify-admin

            echo "Fetching all branches"
            git fetch

            echo "Pulling from master branch"
            git pull origin master

            # Check for merge conflicts
            echo "Checking for merge conflicts"
            if git ls-files -u | grep -q .; then
              echo "Merge conflict detected!"
              exit 1
            else
              echo "No merge conflicts."
            fi

            echo "NVM settings"
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            echo "Use Node 20"
            nvm use 20

            echo "Node version"
            node -v

            echo "NPM version"
            npm -v

            echo "Verify NPM cache"
            npm cache verify

            echo "Clean NPM cache"
            npm cache clean --force

            echo "Installing dependencies"
            npm install

            echo "Building..."
            npm run build

            echo "Copying files to /var/www/bloomify-admin-panel/"
            sudo cp -r dist/* /var/www/bloomify-admin-panel/

            echo "Restarting nginx..."
            sudo systemctl restart nginx
